name: "ci"

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

env:
  NODE_ENV: development

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - uses: actions/cache@main
        with:
          path: |
            ~/.npm
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install dependencies
        run: nix develop --command make install
      - name: Build project
        run: nix develop --command make build
      - name: Run tests
        run: nix develop --command make test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-node-lint-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install dependencies
        run: nix develop --command make install
      - name: Check formatting
        run: nix develop --command pnpm prettier --check .

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-node-coverage-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install dependencies
        run: nix develop --command make install
      - name: Generate code coverage
        run: nix develop --command pnpm run test --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: true
